### ISSUE TITLE
Override global values for ApexCharts in angular

### ISSUE THREAD

**Issue by alarhoo** [apexcharts/ng-apexcharts#103]
Hello, everyone.

I learned that global values of ApexCharts can be overwritten using Apex variable. For instance, [setting locales globally across all charts](https://apexcharts.com/docs/localization/). But, how can we achieve the same in ng-apexcharts.

The variable, window.Apex returns no data for me. Please advice. Thanks in advance.

**Comment by CloudyEMS** [comment]
I solved this by defining `Apex` in a global interface as follows, and then accessing the value from the window object as usual, or by injecting the document object into your component/service.


```typescript
declare global {
  interface Window {
    Apex: any;
  }
}
```

```ts
// component.ts

constructor(@Inject(DOCUMENT) private document: Document) {
  this.document.defaultView.Apex.colors = ['#FF0000', '#00FF00', '#0000FF'];
}
```
