### ISSUE TITLE
Can not set border radius for bar chart

### ISSUE THREAD

**Issue by thienthuatnguyen** [apexcharts/ng-apexcharts#109]
I have read docs of plotOptions and see we can set borderRadius and radiusOnLastStackedBar.
But interface ApexPlotOptions don't have this options. Did you updated it ?

**Comment by junedchhipa** [comment]
I have updated it.
Which version are you using?

**Comment by junedchhipa** [comment]
Try updating to `ng-apexcharts@1.5.7` and `apexcharts@3.24.0`

**Comment by thienthuatnguyen** [comment]
Yeah. It worked, thanks you for support
