### ISSUE TITLE
Angular 11 - Supported by ng-apexcharts?

### ISSUE THREAD

**Issue by alfecu** [apexcharts/ng-apexcharts#112]

**Comment by AKharytonchyk** [comment]
@alfecu so far, no issues. Unfortunately, it seems they're no SSR support as it refers to `window` object without any wrappers.
Using angular 11.1.2

**Comment by rochapablo** [comment]
I'm trying to use with Angular Universal, but it's not working for me.

https://github.com/apexcharts/ng-apexcharts/issues/78
https://github.com/apexcharts/ng-apexcharts/issues/106

**Comment by fnnzzz** [comment]
I managed to solve the problem.
I already have a webpack.config used for building browser/server, so I check for the target there and if it's a server, then I substitute `ng-apexcharts`:

<img width="800" alt="image" src="https://user-images.githubusercontent.com/3502507/112984988-437fb000-9168-11eb-903e-2d28f8a0d7f8.png">

Fake implementation it's original sources, which were taken from https://github.com/apexcharts/ng-apexcharts/tree/master/projects/ng-apexcharts/src/lib (do not forget about adding barrel-file index.ts with exports)

Then I removed `apexcharts` and all `window` using at fake-implementation, and made chart.component dummy.

<img width="476" alt="image" src="https://user-images.githubusercontent.com/3502507/112985420-d4ef2200-9168-11eb-8016-67bb611c1bc2.png">

It allowed to split implementations between browser and server.

**Comment by ankurarora** [comment]
I am getting `window is not defined`. Seems it is not yet supported with SSR. Is there a way out?

**Comment by humanely** [comment]
> I managed to solve the problem. I already have a webpack.config used for building browser/server (`@angular-builders/custom-webpack`), so I check for the target there and if it's a server, then I substitute `ng-apexcharts`:
> 
> <img alt="image" width="800" src="https://user-images.githubusercontent.com/3502507/112984988-437fb000-9168-11eb-903e-2d28f8a0d7f8.png">
> 
> Fake implementation it's original sources, which were taken from https://github.com/apexcharts/ng-apexcharts/tree/master/projects/ng-apexcharts/src/lib (do not forget about adding barrel-file index.ts with exports)
> 
> Then I removed `apexcharts` and all `window` using at fake-implementation, and made chart.component dummy.
> 
> <img alt="image" width="476" src="https://user-images.githubusercontent.com/3502507/112985420-d4ef2200-9168-11eb-8016-67bb611c1bc2.png">
> 
> It allowed to split implementations between browser and server.

Why not make it a part of main package?

**Comment by Higor-Matos** [comment]
> > I managed to solve the problem. I already have a webpack.config used for building browser/server (`@angular-builders/custom-webpack`), so I check for the target there and if it's a server, then I substitute `ng-apexcharts`:
> > <img alt="image" width="800" src="https://user-images.githubusercontent.com/3502507/112984988-437fb000-9168-11eb-903e-2d28f8a0d7f8.png">
> > Fake implementation it's original sources, which were taken from https://github.com/apexcharts/ng-apexcharts/tree/master/projects/ng-apexcharts/src/lib (do not forget about adding barrel-file index.ts with exports)
> > Then I removed `apexcharts` and all `window` using at fake-implementation, and made chart.component dummy.
> > <img alt="image" width="476" src="https://user-images.githubusercontent.com/3502507/112985420-d4ef2200-9168-11eb-8016-67bb611c1bc2.png">
> > It allowed to split implementations between browser and server.
> 
> Why not make it a part of main package?

After scouring the entire internet, your solution was the only one that worked."
