### ISSUE TITLE
Angular > 11.0.0 

### ISSUE THREAD

**Issue by ChiKaLiO** [apexcharts/ng-apexcharts#123]
npm WARN ng-apexcharts@1.5.9 requires a peer of @angular/common@>=9.0.0 <11.0.0 but none is installed. You must install peer dependencies yourself.

It's just a warning, are you planning to support angular 11.x.x ?

**Comment by jhilrdz** [comment]
Same problem.

**Comment by spombinho** [comment]
Same here...it would be nice not to have any warning. Two warnings, one for @angular/ccommon and another for @angular/core.

**Comment by ccravens** [comment]
Would really like to see an update as angular 11 was released several months ago

**Comment by micdenny** [comment]
wouldn't be enough to change this

https://github.com/apexcharts/ng-apexcharts/blob/4d3686de8844615490c788ec6b47c00214ee3e93/projects/ng-apexcharts/package.json#L6-L7

in

```json
    "@angular/common": ">=9.0.0 <12.0.0",
    "@angular/core": ">=9.0.0 <12.0.0",
```

because it seems to be compatible
