### ISSUE TITLE
Possible Unhandled Promise Rejection: TypeError: "i.style is undefined"

### ISSUE THREAD

**Issue by manumohant** [apexcharts/ng-apexcharts#13]
I'm facing issue with this module
Possible Unhandled Promise Rejection: TypeError: "i.style is undefined"

    value apexcharts.min.js:6 value apexcharts.min.js:6 value apexcharts.min.js:6 value apexcharts.min.js:6 value apexcharts.min.js:6 tt apexcharts.min.js:6 q apexcharts.min.js:6 value apexcharts.min.js:6 resizeTimer apexcharts.min.js:6 invokeTask7Angular

COde below
`apexOpt = {
    chart: {
      type: 'line'
    },
    series: [{
      name: 'sales',
      data: [30,40,35,50,49,60,70,91,125]
    }],
    xaxis: {
      categories: [1991,1992,1993,1994,1995,1996,1997, 1998,1999]
    }
  }`

`<apx-chart [series]="apexOpt.series" [chart]="apexOpt.chart" [title]="'title'"></apx-chart>`

**Comment by pchomik** [comment]
@manumohant  I had the same issue. `[title]` is an object of `ApexTitleSubtitle`. May look like that
```
title = {
    text: 'Title',
    align: 'center',
    style: { fontSize: '20px', color: 'red' }
}
```
Here you have full definition:
```
/**
 * Chart Title options
 * See https://apexcharts.com/docs/options/title/
 */
export interface ApexTitleSubtitle {
    text?: string;
    align?: 'left' | 'center' | 'right';
    margin?: number;
    offsetX?: number;
    offsetY?: number;
    floating?: number;
    style?: {
        fontSize?: string;
        color?: string;
    };
}
```

**Comment by junedchhipa** [comment]
Yes, providing a definition for `title` will fix it.
