### ISSUE TITLE
Cannot access viewchild to call methods of the graph

### ISSUE THREAD

**Issue by jegjessing** [apexcharts/ng-apexcharts#138]
Hi

I have a graph, and all is working fine, except when I try to call methods on the graph.
I've named it chart and try to access it as I would in all other angular related situations, but in my case I get 
the HTML code is:
`<div *ngFor="let chartOption of chartOptions;let i=index">
<apx-chart *ngIf="i==selectedChannel" #chart
                     [series]="chartOption.series"
                     [chart]="chartOption.chart"
                     [xaxis]="chartOption.xaxis"
                     [yaxis]="chartOption.yaxis"
                     [stroke]="chartOption.stroke"
                     [title]="chartOption.title"
                     [theme]="chartOption.theme"
                     [colors]="chartOption.colors"
          ></apx-chart>
</div>`

and then I try:
`ngAfterViewInit(): void {
      this.chart.hideSeries(this.chartOptions[0].series[1].name);
  }`

But get, cant call hideSeries on undefined :-( 

Thanks in advamce

**Comment by jegjessing** [comment]
I figured out that the chart is not present until all lines are drawn, so no issue as such, except that is difficult to wait for. A callback, called when the graph is finished drawing would be nice and would solve this issue I think

**Comment by guzel-kabirova** [comment]
@jegjessing  Jarl, Hello! 
More than one year passed from your issue. Did you solve it somehow?
I have the same problem now.

**Comment by jegjessing** [comment]
Sort of. I hacked it with a setTimeout. What I WOULD like is to have a callback like <apx-chart (loadcomplete)="doSomeThingNice()"

But I have not found anything like that..

**Comment by steuf0** [comment]
Hi Jarl.

How exactly did you implement setTimeout to work with hideSeries()?

I've been trying to make a series hidden by default for a couple days now with no success. I always get the same error as you: "can't read properties of undefined reading hideSeries()"

This is my code:

```

@ViewChild('chart', { static: true }) chart!: ChartComponent;

this.chartOptions.series = [
          { name: 'Valor bruto', data: this.original_amounts },
          { name: 'Valor líquido', data: this.amounts },
        ];

ngOnInit(): void { 
    this.hideSeries();
}

  hideSeries() {
    setTimeout(() => {
      this.chart.hideSeries('Valor líquido');
    }, 2000);
  }
```

Would be really nice if we had an option to make a series hidden by default. I need to have a shared tooltip of the values of the two series (gross and net values), but only show gross values bars on the chart. I tried many things but nothing worked so far.
