### ISSUE TITLE
THrowing error when series is null

### ISSUE THREAD

**Issue by manumohant** [apexcharts/ng-apexcharts#14]

**Comment by junedchhipa** [comment]
Please provide a codepen. What are you passing in `series[]` array?

**Comment by manumohant** [comment]
i said im assigning null. With apexchart js its possible and works fine and displays noData message also. But here with this ng-aexchart wrapper, when I try to assign null to series , then Im getting error

**Comment by furyFTW** [comment]
You should pass the ` [{ name: '', data: [] }]`, its working for me.
Also i havent found any input for noData.
The way how to pass and  show noData message :
```
@ViewChild('chartObj') chart: ChartComponent;
....
asapScheduler.schedule(() => {
  this.chart.updateOptions(
    {
      noData: {....} // your no data obj
    },
    false,
    false
  );
}, 1);
```
