### ISSUE TITLE
Data labels not aligning properly

### ISSUE THREAD

**Issue by IgnatG** [apexcharts/ng-apexcharts#151]
Hello
There seems to be an issue with DataLabels being aligned in different positions. See the screenshot below.
![Screenshot 2021-06-04 at 09 29 19](https://user-images.githubusercontent.com/6107088/120772367-270d4480-c518-11eb-84a0-018d4988397c.png)

If I start panning left or right, the location of the label starts to move as well. 
For the purpose of this example I'm using these settings to add the `dataLabels`:
`
      dataLabels: {
         enabled: true,
         textAnchor: 'middle',
         formatter: (val, opts) => 'A'
      }
`

Any ideas as to what may cause this? or how to fix it?

**Comment by junedchhipa** [comment]
Can you create a Codepen so that it can be reproduced?

**Comment by IgnatG** [comment]
Hi @junedchhipa 

I've created a demo on Codesandbox - see link here:
https://codesandbox.io/s/apex-rangebar-timeline-data-labels-qn3wu

I've used one of the rangeBar demos for this

**Comment by IgnatG** [comment]
@junedchhipa do you happen to have any updates on this? Or do you know where the problem may be?
