### ISSUE TITLE
ng-apexcharts histogram plotted as bar chart

### ISSUE THREAD

**Issue by nileshbhagwat** [apexcharts/ng-apexcharts#152]
Plots "Bar Chart" even though chart type is provided as "histogram". Whitespace within Bar is not removed.

![image](https://user-images.githubusercontent.com/22997240/120973405-82e00380-c78c-11eb-8cf9-54a1eec478a5.png)

e.g
https://stackblitz.com/edit/ng-apex-histogram-issue?file=src/app/app.component.ts

Issue looks specific to angular-wrapper, JS demo example works fine
https://stackblitz.com/edit/js-histogram?file=index.html

**Comment by heathervant** [comment]
yes this issue is confusing me too. Is there a shortcut fix for making the bars be close together?

**Comment by nileshbhagwat** [comment]
Currently, we are using patch for this. #220 should resolve this issue
