### ISSUE TITLE
Zoom functionality doesn't work for heatmap chart

### ISSUE THREAD

**Issue by djordjetalovic** [apexcharts/ng-apexcharts#157]
Hello,

I can't get the zoom functionality to work for my heatmap chart. When i set the type property to 'x', which is the default, the x-axis reacts but the data on the grid doesn't change in any way. When i set the type property to 'y' or 'xy' the code breaks with a "Cannot read property 'length' of null' message. i reckon that's because i've set data: [{x: date, y: value}] and the y-axis displays the names of my datasets, so these values probably don't have length properties?

I'm using a heatmap chart with a datetime type  x-axis. I can only show you my chartOptions configuration without the series data, because i generate them dynamically in the following format: 
series: [
  {
  name: data.description,
  data: [{x: data.time, y: data.value}]
}
]

I'm looking for confirmation if zooming is even possible in this configuration, because i saw a stackoverflow post stating that zooming is impossible in heatmap charts, but i wanted to check with you guys.

Thx in advance
<img width="424" alt="Screenshot 2021-06-29 at 12 42 54" src="https://user-images.githubusercontent.com/46373677/123784333-9daf1f00-d8d7-11eb-9429-ecf0865f7be1.png">
<img width="561" alt="Screenshot 2021-06-29 at 12 43 15" src="https://user-images.githubusercontent.com/46373677/123784354-a43d9680-d8d7-11eb-9281-7ff74364950b.png">

**Comment by junedchhipa** [comment]
Unfortunately, zooming on heatmap is not supported.
