### ISSUE TITLE
Add "endingShape" property on plotOptions.bar

### ISSUE THREAD

**Issue by Dogemist** [apexcharts/ng-apexcharts#160]
On the JS version of the library it's possible to make the end of the bar rounded with the property 

`plotOptions: {
        bar: {
          endingShape: "rounded"
        }
      },
`
I see the property is missing the angular version. Is possible to have it also here?
<img width="937" alt="Schermata 2021-08-30 alle 16 27 57" src="https://user-images.githubusercontent.com/22977774/131355131-e53c2c09-5d1c-4ae1-94d9-514618adc1c6.png">

Thanks 🚀

**Comment by junedchhipa** [comment]
Instead of `endingShape`, you can use `borderRadius` property to make rounded borders.
https://apexcharts.com/docs/options/plotoptions/bar/#borderRadius
