### ISSUE TITLE
Graph in Angular Material tabs throws error when resizing (needs destroy())

### ISSUE THREAD

**Issue by michaelpepperwork** [apexcharts/ng-apexcharts#17]
Hi, I have a graph that is contained in an Angular Material tab. Resizing etc. works perfectly while in that tab however if I navigate to another tab and resize the window it throws the following error from the previous graph:

`Error: <path> attribute d: Expected number, "M NaN NaN A   0 0 …"`
`Error: <path> attribute d: Expected number, "M NaN NaN A   0 1 …"`
`Error: <g> attribute transform: Expected number, "translate(NaN, NaN) scale(…"`
`Error: <g> attribute transform: Expected number, "translate(NaN, 20)".`

I suspect this error is being caused by the graph not being destroyed correctly by the component lifecycle hooks. I have confirmed that when navigating to another tab that the graph-containing tab is destroyed (using ngIf) however it appears the graph remains.

So i tried to use the .destroy() method outlined here: 
https://apexcharts.com/docs/methods/#destroy 

with the following code:

@ViewChild('columnChartObj') columnChartObj: ChartComponent;
this.columnChartObj.chart.destroy();

however it seems the destroy method has not been implemented yet. Is that correct of have i misunderstood something?

**Comment by rssaranece94** [comment]
Hi I to need destroy() function.

**Comment by junedchhipa** [comment]
Thanks for reporting.
I have fixed the issue. Will release a patch on npm soon.

**Comment by JaskaranBanga** [comment]
Hi, i am also facing the same issue when are you going to release new version.

**Comment by definitely-unique-username** [comment]
Could you just add ngOnDestroy hook in your ChartComponent class
`
public ngOnDestroy(): void {
  if (Boolean(this.chartObj)) {
    this.destroy();
  }
}
`
