### ISSUE TITLE
Cannot "npm install apexcharts ng-apexcharts --save" to Angular 13.1.X project.

### ISSUE THREAD

**Issue by ezzhop** [apexcharts/ng-apexcharts#180]
Dear Apexcharts/ng-apexcharts 
your package is cannot install to Angular 13.1.4 project, I love and support your project so much. I hope you will fix it sooner. 

`npm install apexcharts ng-apexcharts --save
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: ezzhop@0.0.1
npm ERR! Found: @angular/common@13.1.3
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~13.1.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@">=9.0.0 <13.0.0" from ng-apexcharts@1.6.0
npm ERR! node_modules/ng-apexcharts
npm ERR!   ng-apexcharts@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\kuthc\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:`

**Comment by ezzhop** [comment]
solution found is comment  @ViewChild line out.
// @ViewChild("chart") chart!: ChartComponent | any;

**Comment by junedchhipa** [comment]
Released v1.7.0
