### ISSUE TITLE
Unable to hide legends and remove % value in label

### ISSUE THREAD

**Issue by suriyaJaay** [apexcharts/ng-apexcharts#182]
Hi,
I'm facing below 2 issues.

- Trying to hide legends for pie chart
- Tying to remove % and want to show fixed value.

Here is my [stackoverflow thread](https://stackoverflow.com/questions/70924282/need-help-apex-doughnut-chart-set-fixed-value-in-label-angular)

[minimal repro - stackblitz](https://stackblitz.com/edit/angular-wz13d5?file=src%2Fapp%2Fcard-overview-example.ts)

I tired as per document, but couldn't make it.

Kindly help me to sort this out as stuck up and closing to the deadline :(

**Comment by hasancansaral** [comment]
Neither hiding labels nor dataLabels are working with Angular port.
