### ISSUE TITLE
Chart height does not grow to fill container when excluding x-axis labels

### ISSUE THREAD

**Issue by JustinHoldstock** [apexcharts/ng-apexcharts#19]
Expected:
When setting `xaxis.labels.show` to `false`, the graphed area grows to fill in the area that used to contain the x-axis labels

Actual:
When setting `xaxis.labels.show` to `false`, the graphed area does not grow to fill in the empty space.

Codepen (Set `SHOW_X_LABELS` to false to see it in action):
 https://codepen.io/JimmyKillem/pen/dEZVRa?editors=0110

Screenshots:

**With Label**
<img width="912" alt="Screen Shot 2019-05-21 at 10 51 45 AM" src="https://user-images.githubusercontent.com/763560/58116384-624eac00-7bb9-11e9-9a7a-80f8f8858be8.png">

**Without Label [BUG]**
<img width="908" alt="Screen Shot 2019-05-21 at 10 53 02 AM" src="https://user-images.githubusercontent.com/763560/58116591-ef920080-7bb9-11e9-8359-f989be8a2fee.png">

**Comment by JustinHoldstock** [comment]
Also adding that when you add/remove yaxis labels, this acts as expected

**Comment by junedchhipa** [comment]
Have you tried enabling the sparkline option? If you just want to get rid of x-axis and y-axis labels.

```javascript
chart: {
   sparkline: {
     enabled: true
   }
}
```
https://apexcharts.com/docs/options/chart/sparkline/

**Comment by jholdstock-va** [comment]
@junedchhipa Yup, that does it. I apologize for missing that!

Thanks for the help

**Comment by junedchhipa** [comment]
No worries.
