### ISSUE TITLE
Compilation Issue in Angular Upon importing it in module.ts file

### ISSUE THREAD

**Issue by subash01** [apexcharts/ng-apexcharts#202]
I am new to apex charts I followed the documentation in your official site and tried to implement a simple bar chart, when I am importing <code>import { NgApexchartsModule } from 'ng-apexcharts'</code> this line in my module.ts file and saving it I am getting a lot of compilation issue in angular. Kindly guide me to resolve this.

![image](https://user-images.githubusercontent.com/29374169/158188503-f1de1f4a-ec00-47fc-b90d-dfb8d1bd713b.png)

I had searched a lot of things in internet,but I could not solve it, Kindly help me.

**Comment by milakdev** [comment]
Try locking the library to following versions if you need a quick fix:
    `"apexcharts": "3.33.0"`
    `"ng-apexcharts": "1.6.0"`
