### ISSUE TITLE
Any idea for 'apx-chart' is not a known element?

### ISSUE THREAD

**Issue by MarvinWang** [apexcharts/ng-apexcharts#206]
//My env.
Angular版本：V12
Angular CLI: 12.2.17
Node: 14.17.3
Package Manager: npm 6.14.13
OS: darwin x64
Typescript：4.3.5
IDE Tool：Visual Studio Code

when I followed the steps one, two, three for downloading and installing Apexcharts, I got an error  under the ' <apex-chart></apex-chart>'tag  in the *.component.html like ..

![image](https://user-images.githubusercontent.com/1595207/163213141-08f92c4b-582f-42be-b95d-3c246292dd54.png)

pls tell me how to resolve this issue...

**Comment by tguimmaraess** [comment]
You need to import `NgApexchartsModule` in your `app.modules.ts` file and then, in `@NgModules`, in your `imports`, import the `NgApexchartModule`

**Comment by Noext** [comment]
same error, the solution of [tguimmaraess](https://github.com/tguimmaraess) is not working

**Comment by tguimmaraess** [comment]
> same error, the solution of [tguimmaraess](https://github.com/tguimmaraess) is not working

Could you provide a repository or a link to https://stackblitz.com/?

**Comment by billygerhard** [comment]
The directions say to use 
```
"scripts": [
  "node_modules/apexcharts/dist/apexcharts.min.js"
]
```
but the `min.js` does not exist in the dist folder. use `apexcharts.js` instead in your `angular.json` file.

**Comment by billygerhard** [comment]
I got it working by importing directly into the individual page modules, not into my `app.module.ts`

**Comment by benboughton1** [comment]
I spent too long on this one. 

For me, I jumped the gun and had not declared the component that I was using ngApexChartsModule. Once declared, it all worked as it should... This problem doesn't show up on the stackblitz examples as it is all contained in one module and component. 

E.g. if for using ScatterComponent in a page called Fields: 

```
@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    FieldsPageRoutingModule,
    NgApexchartsModule
  ],
  declarations: [FieldsPage, ScatterComponent],
})
```
