### ISSUE TITLE
ApexFill gradient is missing colorStops

### ISSUE THREAD

**Issue by SimonFavraud** [apexcharts/ng-apexcharts#207]
Hello,

The interface ApexFill doesn't allow me to set a gradient colorStops.

There is a sample of my error :

> 'colorStops' does not exist in type '{ shade?: string; type?: string; shadeIntensity?: number; gradientToColors?: string[]; inverseColors?: boolean; opacityFrom?: number; opacityTo?: number; stops?: number[]; }'.
> 

I've managed to use it by modifyng the interface inside the module, so I guess it might be an oversight

**Comment by MadeleyneSilva** [comment]
another solution for this?
