### ISSUE TITLE
Pass options object - Feature Request 

### ISSUE THREAD

**Issue by Recodify** [apexcharts/ng-apexcharts#21]
Great work on this and apex charts in general, really appreciate the hardwork and love charts. I was just wondering why the decision was made that instead of passing an single Options object to cover all configuration, that we have to pass/bind each type of option (chart, series, legend etc).

It would be easier to consume the apex charts demos if the angular component followed the same pattern of a single options object.

So instead of:

`<apx-chart [series]="chartData" [legend]="lengend" [labels]="labels" [chart]="chart" [plotOptions]="plotOptions" [fill]="fill">`

we would have:

<apx-chart [options]="options">

I've taken a look at the code and see that once the chart is initialized it does build this options object, so why not allow passing it directly?

If you're open to pull requests, let me know and I'll try and make the change but wanted your thoughts before doing so.

**Comment by junedchhipa** [comment]
Good point.
Although that would be a breaking change of the library, it would be easier for future users to configure this way. So, I'm up for it.

In fact, `react-apexcharts` and `vue-apexcharts` follow the pattern of passing the whole configuration object directly. 

This is an example of `react` way of doing it.

```javascript
 <Chart options={this.state.options} series={this.state.series} type="bar" width={500} height={320} />

```

Just 5 props
`series`, `type`, `width`, `height`, `options`

Please take a look at https://apexcharts.com/docs/react-charts#props to look at react wrapper example.

P.S. The `ng-apexcharts` wrapper is dependent on outside contributors as I don't have experience with Angular. So, any improvement is most welcome to make ApexCharts work easier with Angular.

**Comment by j-a-h-i-r** [comment]
Is there any update on this issue? The ability to bind the chartOptions object would greatly improve the development experience
