### ISSUE TITLE
Multiline data labels - not line splitting, showing array as string twice

### ISSUE THREAD

**Issue by CaryTannner** [apexcharts/ng-apexcharts#214]
Thanks for the great library, been able to make some nice charts but I've got an issue with multiline dataLabels.

Using ng-apexcharts and something similar to the code below to make data labels multiline. 

```
dataLabels: {
        textAnchor: 'start',
        style: {
          fontSize: '20px',
          fontWeight: '600',
        },
        dropShadow: {
          enabled: false,
        },
        formatter: (value, { seriesIndex, w }) => {
          // TODO: split over two lines https://github.com/apexcharts/apexcharts.js/issues/670

          return [`${w.config.labels[seriesIndex]}`, `${value}%`] as unknown as string;

        },
      },
```

In my case, they are for pie charts

<img width="666" alt="image" src="https://user-images.githubusercontent.com/79838560/170032978-bb6c1285-02b7-4c86-b4d1-3f2aa30f1a54.png">

The problem I am having even shows up in some of your documentation examples (different function but I imagine they are conencted):  
https://apexcharts.com/angular-chart-demos/column-charts/distributed-columns/

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/79838560/170031105-81749237-0802-404b-8c85-9b126c5e9049.png">

Any ideas/work arounds  would be much appreciated, thanks

**Comment by junedchhipa** [comment]
Please update apexcharts to v3.35.3 which fixes this issue.
