### ISSUE TITLE
Show tooltip in top of center chart with value [Object object]

### ISSUE THREAD

**Issue by AndoruKun** [apexcharts/ng-apexcharts#225]
Hi so im using Mixed Type Column and Line

im follow all of instruction in demo section

if i remove option tooltip its gone but i want to use tooltip to show value of per category

here what i got
<img width="416" alt="Screen Shot 2022-08-19 at 18 16 15" src="https://user-images.githubusercontent.com/25896815/185607090-aa390097-7522-4dc5-bd22-8da756d73d42.png">

and this is my option

`this.chartOptions4 = {
            series: [
                {
                    name: "New Employee",
                    type: "column",
                    data: [20, 29, 37, 36, 44, 45, 50, 58],
                    color: "#F03A68"
                },
                {
                    name: "Revenue",
                    type: "line",
                    data: [20, 29, 37, 36, 44, 45, 50, 58],
                    color: '#B93B3B'
                }
            ],
            chart: {
                height: 350,
                type: "line",
                toolbar: {
                    show: false
                }
            },
            labels: [],
            plotOptions: {
                bar: {
                    borderRadius: 5
                }
            },
            dataLabels: {
                enabled: false
            },
            stroke: {
                width: [1, 1, 4]
            },
            markers: {
                size: 6,
                hover: {
                    size: 10
                }
            },
            yaxis:{
                axisTicks: {
                    show: false
                },
                axisBorder: {
                    show: true,
                    color: "#7A7A7A"
                },
                labels: {
                    style: {
                        colors: "#7A7A7A"
                    }
                },
                tooltip: {
                    enabled: false
                }
            },
            xaxis: {
                tooltip: {
                    enabled: false
                }
            },
            tooltip: {
                enabledOnSeries: [0],
                theme: 'dark',
                marker: {
                    show: false,
                },
                items: {
                    display: 'flex',
                },
                fixed: {
                    enabled: true,
                    position: 'topRight',
                    offsetX: 0,
                    offsetY: 0,
                },
            },
            legend: {
                show: false,
            }
        };`

can you guys help me whats wrong with my config

thank you

**Comment by DD-8** [comment]
Hi,
Did you find any solution for this? I have the same problem.

**Comment by ligiane** [comment]
Same problem here...

**Comment by ligiane** [comment]
After a long time investigating the problem, I found a conflict between apexcharts tooltip and bootstrap tooltip.

The problem was solved  with this css, which hides the bootstrap tooltip:

.tooltip.bs-tooltip-top.show {
  display: none !important;
}

**Comment by jlavric** [comment]
@ligiane thank you for this solution. I was trying to extend ApexTooltip directive or create one or alias but with no success. Now I am adding this selector to components CSS. Ngx-bootstrap should rename their directive to bsTooltip. I guess :)
Thank you again!!
