### ISSUE TITLE
event selection unable to use

### ISSUE THREAD

**Issue by Yogeshbluepi** [apexcharts/ng-apexcharts#23]
how to use event function in ng-apexcharts ?

**Comment by junedchhipa** [comment]
What are you trying to do?
Are you referring to the ApexChart's event `chart.events.selection`?
```javascript
chart: {
  events: {
    selection: (chart, e) => {
      console.log(new Date(e.xaxis.min))
    }
  }
}
```

**Comment by kzkpro** [comment]
is there any solution for this?
