### ISSUE TITLE
Heatmap color based on Data range.

### ISSUE THREAD

**Issue by MartiinnDev** [apexcharts/ng-apexcharts#235]
Hello, I'm facing the same situation than other user 3 years ago: https://github.com/apexcharts/apexcharts.js/issues/321

I cannot find any solution to this, I need to color each square based on 3 different colors, based on a range from 0 to 100 (not shade)

For example, from 15 to 40 green, 40 to 75 yellow, 75 to 100 on red.

Can I ask you to guide me how to do it if you already added that feature? Thank you so much

**Comment by yibb-y** [comment]
https://apexcharts.com/angular-chart-demos/heatmap-charts/color-range/

They have an example here
