### ISSUE TITLE
Support for Angular v14 with rxjs 7

### ISSUE THREAD

**Issue by kristofdc** [apexcharts/ng-apexcharts#236]
Is there already support for Angular v14 with RXJS 7 ?
I have an app that uses a framework that references the rxjs 7.5.5 version. 
Can I already work with Angular v14 and ng apexchart, when ngapexchart is pointing to rxjs 6.5.5 in latest version (v1.7.4)?

**Comment by jbpzen** [comment]
I'm currently working with Angular 14+, RxJS 7+ and the latest ng-apexcharts and it seems to work properly.

**Comment by sasikamiyuran** [comment]
Can anyone share a project on Stackblits by Angualr 14

**Comment by damingerdai** [comment]
> 

[hoteler-web](https://github.com/damingerdai/hoteler-web) or [ng-matero](https://github.com/ng-matero/ng-matero)

**Comment by damingerdai** [comment]
> [hoteler-web](https://github.com/damingerdai/hoteler-web) or [ng-matero](https://github.com/ng-matero/ng-matero)

[hoteler-web](https://github.com/damingerdai/hoteler-web) or [ng-matero](https://github.com/ng-matero/ng-matero)

**Comment by damingerdai** [comment]
> Can anyone share a apexchart project on Stackblitz by Angualr 14

[hoteler-web](https://github.com/damingerdai/hoteler-web) or [ng-matero](https://github.com/ng-matero/ng-matero)
