### ISSUE TITLE
Support Angular 8

### ISSUE THREAD

**Issue by mits87** [apexcharts/ng-apexcharts#24]
Hi,

can you support Angular 8 as well?
Now I have:

```
npm WARN ng-apexcharts@1.0.5 requires a peer of @angular/common@^7.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng-apexcharts@1.0.5 requires a peer of @angular/core@^7.1.0 but none is installed. You must install peer dependencies yourself.
```

Thank you!

**Comment by sp90** [comment]
We have it working in angular 8, even though it says it requires v 7.1.0 - so might just be the dependencies in the package.json that needs an update, depending on the code in this project

**Comment by mits87** [comment]
yes, it is a dependency of package.json but it will be good if the versions will bump up. What do you think?

**Comment by sp90** [comment]
Agreed but I haven't fully tested everything on angular 8 so I tbh I don't know if it's a good idea - maybe a repo contributer should test and update

**Comment by junedchhipa** [comment]
The next release will be Angular 8 compatible
