### ISSUE TITLE
Feature request: "Smooth" line style for radar charts

### ISSUE THREAD

**Issue by 0x4a61636f62** [apexcharts/ng-apexcharts#246]
I have a use case where I need a "smooth" line for a radar plot. Would it be challenging to add to the library?

In chart.js it is possible to add a `tension` property to the line style:
https://www.chartjs.org/docs/latest/charts/line.html#line-styling

I am using chart.js to do what I want but I would prefer to use `ng-apexcharts` if possible.

**Comment by dvalley56** [comment]
In the chartOptions add the following
```
 stroke: {
      ...
      curve: "smooth",
      ...
    },
```

You can see the interface file for available options
```
export interface ApexStroke {
    show?: boolean;
    curve?: "smooth" | "straight" | "stepline" | ("smooth" | "straight" | "stepline")[];
    lineCap?: "butt" | "square" | "round";
    colors?: string[];
    width?: number | number[];
    dashArray?: number | number[];
    fill?: ApexFill;
}
```
