### ISSUE TITLE
Need help creating a circular (round) shaped radar chart

### ISSUE THREAD

**Issue by gibmax** [apexcharts/ng-apexcharts#248]
Hello, I am trying to create a radar chart with 4 values. The radar chart is working. I need help with changing the axis shape of the chart from polygon to circular. Is this possible with radar chart in Apex Charts? 

Reference Link: 
https://stackoverflow.com/questions/57188029/is-it-possible-to-produce-circular-round-shaped-radar-chart-in-chart-js

Thank you!

**Comment by rojofan** [comment]
HI @junedchhipa, 
I'm looking to have similar results, is there any chance for the team to consider implementing a circular shape for the Radar? 
Cheers
