### ISSUE TITLE
plotOptions property seems to have no effect in Angular

### ISSUE THREAD

**Issue by mw108** [apexcharts/ng-apexcharts#257]
These two examples are equal. While the `plotOptions` property works as expected in the JavaScript version, it seems to be ignored in the Angular version.

JavaScript:
https://codepen.io/mw-108/pen/ExeRYer

![grafik](https://user-images.githubusercontent.com/6154158/225601083-cb3a2555-47cd-47ef-9bc7-4a1c91cd384c.png)

Angular:
https://codesandbox.io/s/gifted-cloud-pxvvc3?file=/src/app/app.component.ts

![grafik](https://user-images.githubusercontent.com/6154158/225601268-c8431a1d-ae07-4f2b-b7e9-c03a525da4a2.png)

**Comment by mw108** [comment]
No feedback here in over 1 month. Am I the only one having this issue? Is it an issue with ngApexCharts or an error on my side?

**Comment by caboodal** [comment]
I've tried and I can't get the plotOptions to have any impact either and I cannot turn off the dataLabels either and I'm using the latest 1.9.0 release

**Comment by mw108** [comment]
I abandoned Apexcharts and switched to Apache ECharts: https://echarts.apache.org/en/index.html

**Comment by caboodal** [comment]
after a bit more investigation I realised that I wasn't binding the option classes to the chart!

So to clarify everything is working perfectly.

**Comment by mw108** [comment]
I see, you are right. Wow. Such a simple pitfall. 🙈 

`
<div id="chart-wrap">
  <apx-chart
    id="chart"
    [series]="chartOptions.series"
    [chart]="chartOptions.chart"
    **[plotOptions]="chartOptions.plotOptions"** <-- Add this
    [dataLabels]="chartOptions.dataLabels"
    [markers]="chartOptions.markers"
    [title]="chartOptions.title"
    [fill]="chartOptions.fill"
    [stroke]="chartOptions.stroke"
    [colors]="chartOptions.colors"
    [legend]="chartOptions.legend"
    [yaxis]="chartOptions.yaxis"
    [xaxis]="chartOptions.xaxis"
    [tooltip]="chartOptions.tooltip"
    [grid]="chartOptions.grid"
    [autoUpdateSeries]="false"
  ></apx-chart>
</div>
`
