### ISSUE TITLE
ApexChart does not work when using Tabs components in the latest version, it only works in version 3.22.3

### ISSUE THREAD

**Issue by diogosilvasantana** [apexcharts/ng-apexcharts#260]
Good afternoon

I'm working on an Angular project where I'm using a stacked column chart. On my screen, I use the Tab component, where the Tab's content has this graphic.

However, in the latest version of ApexChart, when changing the tab, the chart is not rendered, only appearing when I resize the browser screen and when returning to the previous tab, the same thing happens.

To solve it at the moment, I had to downgrade the ApexChart version to **version 3.22.3** which works normally.

Has anyone had the error? Do you have any plans for an update to fix this issue?

**Comment by phoenixcoded20** [comment]
I have the same issue. Any solution so far?

**Comment by diogosilvasantana** [comment]
> I have the same issue. Any solution so far?

There is currently no solution.

The only solution I found was to use version 3.22.3 which works normally.

Downgrade the version to 3.22.3

**Comment by jivanf** [comment]
I was also having the exact same issue and I was able to fix it by [lazy loading](https://material.angular.io/components/tabs/overview#lazy-loading) the chart. That looks something like this:

```html
<mat-tab-group>
    <mat-tab>
        <ng-template matTabContent>
            <!-- Chart goes here -->
        </ng-template>
    </mat-tab>
</mat-tab-group>
```

Hope it helps!
