### ISSUE TITLE
Latest update of ng-apexcharts to angular v15

### ISSUE THREAD

**Issue by Suryaprasath1996** [apexcharts/ng-apexcharts#276]
Hi, currently i am facing below issue in gitlab but its working fine in local.
I am facing this issue past 4 days only, before that its working fine. 
So which version of ng-apexcharts can we use for angular 12 project? I am using angular 12 project

./node_modules/ng-apexcharts/fesm2015/ng-apexcharts.mjs - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
TypeError: Cannot create property 'message' on string '/app/node_modules/ng-apexcharts/fesm2015/ng-apexcharts.mjs: This application depends upon a library published using Angular version 15.2.9, which requires Angular version 14.0.0 or newer to work correctly.
Consider upgrading your application to use a more recent version of Angular.

**Comment by Jonatasmz** [comment]
i have the exactly same problem. Tried to update to angular 13, but still doesnt work

**Comment by damingerdai** [comment]
> @junedchhipa @damingerdai can you please check this one

try to use [ng-apexcharts@v1.6.0](https://www.npmjs.com/package/ng-apexcharts/v/1.6.0)

**Comment by damingerdai** [comment]
> i have the exactly same problem. Tried to update to angular 13, but still doesnt work

what version is the ng-apexcharts used?

**Comment by Suryaprasath1996** [comment]
Hi @damingerdai 
Myself tried almost all the version. but same error got in gitlab. I tried v1.6.0 and even 1.2.2. 
In local its working fine, only error got in gitlab only.
So is there any specific version can we use for apexcharts version with ng-apexcarts 1.6.0.

**Comment by damingerdai** [comment]
> Hi @damingerdai Myself tried almost all the version. but same error got in gitlab. I tried v1.6.0 and even 1.2.2. In local its working fine, only error got in gitlab only. So is there any specific version can we use for apexcharts version with ng-apexcarts 1.6.0.

https://github.com/damingerdai/angular12-apexcharts-app, it works for me

**Comment by damingerdai** [comment]
if you use angular 13, please use 1.7.0

**Comment by Suryaprasath1996** [comment]
HI @damingerdai 
For me also working fine in local environment, only got build error like below in gitlab
![image](https://github.com/apexcharts/ng-apexcharts/assets/58415186/13584bfe-d9c9-4c51-8c27-f05c6c6a1d4c)

**Comment by Suryaprasath1996** [comment]
Hi @damingerdai 
I am only installed ng-apexcharts and apexcharts alone, i am not importing apxchartsmodule also, just install two apexcharts library alone, but that also i got error in gitlab like below.
![image](https://github.com/apexcharts/ng-apexcharts/assets/58415186/cd7cd8ae-4783-442a-9f46-2f8f5f814d64)
![image](https://github.com/apexcharts/ng-apexcharts/assets/58415186/cfded003-ee06-4c86-b0be-dd20f84f7bea)

**Comment by Suryaprasath1996** [comment]
If I import module, then i am getting below error
![image](https://github.com/apexcharts/ng-apexcharts/assets/58415186/e7de5c06-0978-45cb-92c2-f283f4dc8db7)

**Comment by Suryaprasath1996** [comment]
Hi @damingerdai 
Here it is ng version
![image](https://github.com/apexcharts/ng-apexcharts/assets/58415186/a5dc0f0c-ac31-4d3e-88c2-51d8429e5f63)

**Comment by damingerdai** [comment]
check your loke file,
you do not use ng-apexcharts 1.6.0,

please use:

```
    "apexcharts": "3.31.0",
    "ng-apexcharts": "1.6.0",

```

**Comment by damingerdai** [comment]
you look like using 1.8.0

**Comment by Suryaprasath1996** [comment]
Hi @damingerdai 
Thanks for the input now its working when I change the library version from **^**1.6.0 to **~**1.6.0.
Thanks for the your input and time
