### ISSUE TITLE
angular 17 support

### ISSUE THREAD

**Issue by damingerdai** [apexcharts/ng-apexcharts#292]

**Comment by ottopic** [comment]
Thanks for this beautiful Angular wrapper. What's about this bump?

**Comment by caboodal** [comment]
do we need to use ngx-apexcharts for Angular 17 or does the documented ng-apexcharts now work?

**Comment by ottopic** [comment]
> do we need to use ngx-apexcharts for Angular 17 or does the documented ng-apexcharts now work?

I'm using ngx-apexcharts

**Comment by junedchhipa** [comment]
Released `ng-apexcharts@1.9.0`

**Comment by caboodal** [comment]
My charts are now working using Angular 17, Signals and NgRx Signal Store!

Thank you!

Also if anybody stumbles across this issue don't forget to add the `NgApexchartsModule` import into your component imports if you're using standalone components.
