### ISSUE TITLE
Add stackOnlyBar to angular library

### ISSUE THREAD

**Issue by leomartinsm** [apexcharts/ng-apexcharts#308]
In the Javascript library and in the doc, the property of only the bar being stacked was added 

i’m using the latest version available on npm 1.8.0

but i saw that you already performed a merge into master with this change in git 

Do you have any predictions for the release of the new version on npm?

**Comment by leomartinsm** [comment]
![Uploading IMG_1912.png…]()

**Comment by leomartinsm** [comment]
@junedchhipa plis can you help me

**Comment by junedchhipa** [comment]
The latest version 1.11.0 has this covered.
