### ISSUE TITLE
dataPointIndex is always -1 for events triggered on a pie chart

### ISSUE THREAD

**Issue by Pyknic** [apexcharts/ng-apexcharts#328]
I have created a pie chart with this config:
```typescript
this.config = {
    chart: {
      ...this.defaultChartConfig(),
      events: {
        click(e: any, chart?: any, options?: any) {
          console.log('Click. Series index: ' + options.seriesIndex + ', data point index: ' + options.dataPointIndex);
        }
      }
    }
  };
```

Series index and data point index is always -1. For bar charts, it works as expected.

**Comment by junedchhipa** [comment]
Can you please try with the latest apexcharts version and test again?
Also, provide a codepen example in case it didn't work.

**Comment by blogcraft** [comment]
click always return -1 for me too. use dataPointSelection instead
