### ISSUE TITLE
Incorrect ApexAxisChartSeries interface

### ISSUE THREAD

**Issue by definitely-unique-username** [apexcharts/ng-apexcharts#33]
Looks like you have wrong interface. It should be like like this:
```
export declare type ApexAxisChartSeries = {
    name: string;
    **type?: ChartType;**
    data: number[] | {
        x: string;
        y: number;
    }[];
}[];
```

[Link to docs](https://apexcharts.com/javascript-chart-demos/mixed-charts/line-area/)

**Comment by junedchhipa** [comment]
Thanks for reporting, yes it is wrong. I will update it soon.
