### ISSUE TITLE
bump angular 18

### ISSUE THREAD

**Issue by damingerdai** [apexcharts/ng-apexcharts#331]

**Comment by dabbabi** [comment]
ERESOLVE unable to resolve dependency tree

While resolving: project@1.0.0
Found: @angular/common@18.0.0
node_modules/@angular/common
  @angular/common@"^18.0.0" from the root project

Could not resolve dependency:
peer @angular/common@"^17.0.2" from ng-apexcharts@1.10.0
node_modules/ng-apexcharts
  ng-apexcharts@"^1.10.0" from the root project

Fix the upstream dependency conflict, or retry this command with --force or --legacy-peer-deps to accept an incorrect (and potentially broken) dependency resolution.

**Comment by Erkam246** [comment]
please bump for angular 18

**Comment by liqMats** [comment]
+1

**Comment by ottopic** [comment]
How to update it? I have the same problem of update

**Comment by instantgis** [comment]
me too

**Comment by damingerdai** [comment]
I forked the project and renamed it to ngx-apexcharts. It provides support for angular 18. Before ng-apexcharts officially supports angular 18, you can use ngx-apexcharts as a transition.

**Comment by reyvaxreecded** [comment]
+1

**Comment by alanvitor-university** [comment]
+1 please

**Comment by jdlee726** [comment]
+1

**Comment by YuriiDmytryshyn** [comment]
+1 please

**Comment by nook24** [comment]
+1

**Comment by michaelkrog** [comment]
Simply add this to your package.json for now:
```
  "overrides": {
    "ng-apexcharts": {
      "@angular/common": ">17.0.2",
      "@angular/core": ">17.0.2"
    }
  }
```

Will force the dependency of ng-apexcharts to span over major versions.

**Comment by YuriiDmytryshyn** [comment]
thanks, I did it

пн, 17 черв. 2024 р. о 17:15 Michael Krog ***@***.***> пише:

**Comment by nook24** [comment]
Many thanks @michaelkrog that worked for me

**Comment by YuriiDmytryshyn** [comment]
Awesome, thanks for the update!

вт, 18 черв. 2024 р. о 17:29 Juned Chhipa ***@***.***> пише:
