### ISSUE TITLE
Request for Canvas Rendering Option

### ISSUE THREAD

**Issue by Sariln** [apexcharts/ng-apexcharts#333]
I would like to request the addition of a Canvas rendering option in ApexCharts. Currently, ApexCharts uses SVG for rendering charts, which is great for static or semi-static visualizations. However, for use cases involving frequent updates, animations, or large datasets, Canvas rendering could potentially provide better performance compared to SVG.

Canvas is a pixel-based rendering method that can handle frequent redrawing and manipulations more efficiently than SVG, which treats each element as a separate DOM node. This could be beneficial for real-time data visualizations, animations with many moving objects, or visualizing large datasets.

While Canvas has trade-offs compared to SVG, offering a Canvas rendering option alongside the existing SVG rendering could cater to a wider range of use cases where performance is a priority.

Thank you for considering this feature request.

**Comment by junedchhipa** [comment]
Sorry, but that would require a major rewrite of the library. Both SVG and canvas uses a very different way of drawing shapes, so interchanging one with the other wouldn't be possible.
