### ISSUE TITLE
Issue with Apex plot options.

### ISSUE THREAD

**Issue by rossum-computing** [apexcharts/ng-apexcharts#34]
HELLO, I am using your NG-APEXCHARTS library. Thank you very much for this. I have found a Bug , it would be great if you could fix this. So, the bug is about the Apex plot options of the Radial bar chart. It has an option to give Dropshadow, however, this option is not present in the angular library, that option is throwing an error and also it is getting rendered to and casting a shadow.

**Comment by rossum-computing** [comment]
Also endingShape option is not available in radialbar.

**Comment by saicharanallam** [comment]
size?: number;
        inverseOrder?: boolean;
        startAngle?: number;
        endAngle?: number;
        endingShape?: string;
        offsetX?: number;
        offsetY?: number;
        hollow?: {
            margin?: number;
            size?: string;
            background?: string;
            image?: string;
            width?: number;
            height?: number;
            offsetX?: number;
            offsetY?: number;
            clipped?: boolean;
            position?: "front" | "back";
            dropShadow?: {
                enabled?: boolean;
                top?: number;
                left?: number;
                blur?: number;
                opacity?: number;
            };
        };

**Comment by saicharanallam** [comment]
If we update the library file with the above code, the issue will be fixed. Can I become a contributor?

**Comment by junedchhipa** [comment]
@saicharanallam Sure, a PR is always welcome.

**Comment by junedchhipa** [comment]
The `dropShadow` is already present in the latest version - https://cdn.jsdelivr.net/npm/ng-apexcharts@1.1.2/lib/model/apex-types.d.ts

Can you please ensure you are using the latest version?

**Comment by junedchhipa** [comment]
> Also endingShape option is not available in radialbar.

Yes, endingShape is not possible for radialBar.
