### ISSUE TITLE
Cannot create property 'hidden'

### ISSUE THREAD

**Issue by adilorenzodema** [apexcharts/ng-apexcharts#354]
Hi, I've this issue when click on legend for disable label:

![image](https://github.com/user-attachments/assets/ece1e6a4-7580-4f2c-b1f4-a93e4bac9a26)

This is my version:
"ng-apexcharts": "1.7.7",
"@angular/core": "~13.3.0",
"@angular/cli": "~13.3.11",

This is my configuration on component ts:
![image](https://github.com/user-attachments/assets/8a5bb184-6741-4abe-87bb-4cfaa132216b)
![image](https://github.com/user-attachments/assets/c41f73ef-754d-4eb4-8965-f8444ba78455)
![image](https://github.com/user-attachments/assets/33122e3d-1bdf-47c1-8745-c5cf3ea723fc)

This on html.
![image](https://github.com/user-attachments/assets/c5ec908a-d047-4c96-8a7d-a307443f12b3)

Can you help me?

**Comment by junedchhipa** [comment]
Please provide a reproducible codesandbox

**Comment by AQM19** [comment]
I've the same issue and I don't know why it's happening. There's any solution?

**Comment by junedchhipa** [comment]
Please try upgrading to latest versions of `apexcharts@4.1.0` and `ng-apexcharts@1.15.0`
