### ISSUE TITLE
support angular 19

### ISSUE THREAD

**Issue by damingerdai** [apexcharts/ng-apexcharts#366]

**Comment by thijsvm** [comment]
Not the best solution but for now I've modified the package.json of my angular project like this:
```json
{
  //...
  "dependencies": {
    // ...
    "apexcharts": "^3.49.1",
    "ng-apexcharts": "^1.11.0",
  },
  "overrides": {
    "ng-apexcharts": {
      "@angular/common": "^19.0.0",
      "@angular/core": "^19.0.0"
    }
  }
}

```
I'm not using the latest version of ng-apexcharts because I also have this issue: https://github.com/apexcharts/ng-apexcharts/issues/367
