### ISSUE TITLE
Does not install on angular 19

### ISSUE THREAD

**Issue by ranashahan** [apexcharts/ng-apexcharts#371]
While installing `npm i ng-apexcharts`  it I got the following error 

> npm error Found: @angular/common@19.0.0
> npm error node_modules/@angular/common
> npm error   **@angular/common@"^19.0.0"** from the root project
> npm error
> npm error Could not resolve dependency:
> npm error peer **@angular/common@"^18.0.4"** from ng-apexcharts@1.13.0
> npm error node_modules/ng-apexcharts
> npm error   ng-apexcharts@"*" from the root project

**Comment by Sergi0Martin** [comment]
Same here, after migrate my project to angular 19 I got this error.
It is planed the compatibility upgrade?

**Comment by junedchhipa** [comment]
Please try `ng-apexcharts@1.14.0` and report here if it worked

**Comment by ducanhtk5** [comment]
> Please try `ng-apexcharts@1.14.0` and report here if it worked

I received error:
[ERROR] File 'node_modules\ng-apexcharts\src\lib\chart\chart.component.ts' is missing from the TypeScript compilation.

**Comment by damingerdai** [comment]
please try to use [ngx-apexcharts](https://www.npmjs.com/package/ngx-apexcharts?activeTab=readme) as temp solution

**Comment by ranashahan** [comment]
It worked on V1.15.0 on the Angular 19 project, Awesome and very efficient support & fixing.. Thank you. 

> npm i ng-apexcharts
> 
> added 1 package, and audited 983 packages in 4s
> 
> 155 packages are looking for funding
>   run `npm fund` for details
> 
> found 0 vulnerabilities
