### ISSUE TITLE
horizontal bar layout/styling issue

### ISSUE THREAD

**Issue by kudoR** [apexcharts/ng-apexcharts#40]
Hello,
im trying to do a simple horizontal bar chart, however, the first bar at the top of the screen will be cut off and it seems all the bars are somehow shiftet and not at the right place.
i created a small stackblitz: https://stackblitz.com/edit/angular-ajihze

any help or fix would be appreciated :-)

**Comment by junedchhipa** [comment]
Sorry for the late response.
You didn't provide xaxis attribute in a horizontal bar chart, hence it was not rendering correctly.
Here is the updated stackblitz: https://stackblitz.com/edit/angular-abi4da
