### ISSUE TITLE
Chart is not being destroyed when parent component destroyed

### ISSUE THREAD

**Issue by srcn** [apexcharts/ng-apexcharts#41]
When you destroy a parent component that has an `<apx-chart>` in it, the underlying ApexChart is not being destroyed. That causes errors on page resize since the component is still active but not on the DOM anymore. It's also causing a memory leak.

Here's a Stackblitz link for the reproduction: [Stackblitz](https://stackblitz.com/edit/ngapexcharts-destroy-issue?file=src%2Fapp%2Fcomponents%2Froute1.component.ts)

To reproduce the issue;

1. Open the Console from your browser's dev tools since Stackblitz's console doesn't catch the error.
1. Go to **Route1** to initialize the chart
2. Go to **Route2** and then resize the preview pane.
3. Errors will be printed on the console

In the example, if I destroy the ```ChartComponent``` manually on ```Route1Component```'s `ngOnDestroy` hook, everything works perfectly fine.

Is there a reason that the
```js
this.chartObj.destroy();
```
is not being called on `ngOnDestroy` of the `ChartComponent`?

I've also checked the Vue wrapper of the ApexCharts and it seems that the `chart.destroy()` method is being called on the `beforeDestroy()` lifecycle hook of the component to properly destroy the chart: [vue-apexcharts component #L61](https://github.com/apexcharts/vue-apexcharts/blob/578445d87d979857db65dcb9817bdee6591f19cf/src/ApexCharts.component.js#L61)

**Comment by junedchhipa** [comment]
Good catch.
Yes, it should be there.
Can you please create a PR for this? I have less experience with Angular, so not sure how this should be handled.

**Comment by srcn** [comment]
@junedchhipa Yes, that would be enough. I can still create a PR if you want, but it's a very small fix so I just wanted to let you know rather than creating a PR.

**Comment by junedchhipa** [comment]
Thanks, fixed it.
I will release a patch version soon.

**Comment by srcn** [comment]
Thank you!

**Comment by srcn** [comment]
Forgot to mention that you also need to import and implement `OnDestroy`:

```js
import {
  ...
  OnInit,
  OnDestroy
  ...
} from "@angular/core";

export class ChartComponent implements OnInit, OnChanges, OnDestroy
```

--

Next time I'll create a PR if I find something.

**Comment by junedchhipa** [comment]
No problem, I added it.
Yes, I appreciate any contributions to the ng-apexcharts repo.

**Comment by BrummbQ** [comment]
Can you please release this fix?
