### ISSUE TITLE
question: render png in the backend?

### ISSUE THREAD

**Issue by reza-iranmanesh** [apexcharts/ng-apexcharts#42]
Hi,

Is there anyway to use ApexCharts in backend and create and download and save the static PNG in a Node or NestJs installation?

**Comment by junedchhipa** [comment]
Sorry, generating charts on the server is not possible with ApexCharts.

You may take a look at [FusionExport](https://www.fusioncharts.com/fusionexport?utm_source=github&utm_medium=github_issues&utm_campaign=apexcharts&utm_content=fusionexport), a product from our partner FusionCharts to achieve this.
More info - https://apexcharts.com/docs/export-to-pdf-in-node-js/
