### ISSUE TITLE
Performance for large dataset

### ISSUE THREAD

**Issue by aryanPatilhm2** [apexcharts/ng-apexcharts#44]
Hi.. I am using an apex chart with multiple Y axis. Today I have a problem with large data set. It works perfectly if my dataset is less than 100 points for each line chart. But above that, it stuck to load data and some time after page becomes unresponsive. On the features page of apexcharts(https://apexcharts.com/features/), they have shown support of rendering a large number of data points. (25000 point) but I cant . For showing the problem,  I used the below stackblitz page.

https://stackblitz.com/edit/ngapexcharts-demo

Just replace below function in demo,
```
addSeries() {
  this.data = []
  this.xData = []

  for(var i=0;i<10000;i++){
    this.data.push(new FormControl(this.getRandomArbitrary(0, 100)))
    this.xData.push(new FormControl(i))
  }

  this.form = new FormGroup({
      title: new FormControl('Basic Chart'),
      type: new FormControl('line'),
      height: new FormControl(350),
      series: new FormArray([
        new FormGroup({
          name: new FormControl('Series'),
          type: new FormControl('line'),
          data: new FormArray(this.data)
        })
      ]),
      xaxis: new FormArray(this.xData)
    });
  }
```
and click on **Add series** button.
Will you please help me regarding this problem?
Thanks in advance..!!

**Comment by junedchhipa** [comment]
For maximizing performance, turn off animations, data-labels, markers, etc.

```javascript
chart: {
  animations: {
    enabled: false
  }
},
markers: {
   size: 0
}
```

**Comment by MetaNodo** [comment]
> For maximizing performance, turn off animations, data-labels, markers, etc.
> 
> ```js
> chart: {
>   animations: {
>     enabled: false
>   }
> },
> markers: {
>    size: 0
> }
> ```

Muchas gracias por la aportación. Vine porque el volumen de datos que cargo es considerable, lo aplique y bajo el tiempo de carga extremadamente. Lo pueden ver en [acciones Banco Sabadell](https://foro.trading/acciones-banco-sabadell/), tarda muy poco a ahora.

**Comment by sheikh303** [comment]
the pie chart still animated (clockwise drawing on-load) after applying animations: false and markers size 0; 
the bar charts working fine though for this configuration. 
Please help.
My code in react:
```
Chart = require('react-apexcharts').default

    this.state = {
      options: {
        tooltip: {
          enabled: false,
        },
        plotOptions: {
          pie: {
            donut: {
              size: '60%',
              labels: {
                show: true,
                name: {
                  show: false,
                },
                value: {
                  show: true,
                  offsetY: 5,
                  fontFamily: 'Salesforce Sans Bold',
                  fontSize: '20px',
                  formatter: value => {
                    return `${value} %`
                  },
                },
                total: {
                  show: true,
                  showAlways: true,
                  formatter: value => {
                    return `${value.globals.seriesTotals[0]}%`
                  },
                },
              },
            },
          },
        },
        labels: [`Completed`, `Not Completed`],
        colors: ['#2A82BE', '#DBEBF8'],
        dataLabels: {
          enabled: false,
        },
        legend: {
          show: false,
        },
      },
      series: [percentCompleted, percentNotCompleted],
      chart: {
        animations: {
          enabled: false,
        },
      },
      markers: {
        size: 0,
      },
    }

<Chart
            options={this.state.options}
            series={this.state.series}
            type="donut"
            height={260}
          />
```

**Comment by JuanRomeroDominguez** [comment]
La propiedad chart (que incluye animations) debe estar dentro del objeto options, no al mismo nivel que series. En el grafico de estadísticas del [calendario](https://calendario.gratis) lo aplico y funciona para mi. Saludos.
