### ISSUE TITLE
Update ApexTooltip interface to support enabledOnSeries property

### ISSUE THREAD

**Issue by bodn** [apexcharts/ng-apexcharts#45]
Hi, this is my first time ever submitting an issue to an open source project. Please feel free to delete if unnecessary.

 

**Issue:** ApexTooltip does not support the correct type for the enabledOnSeries property

 

**Currently:** `export interface ApexTooltip {
...
    enabledOnSeries?: undefined | boolean;
...
}`

 

Apex Docs: [https://apexcharts.com/docs/options/tooltip/](https://apexcharts.com/docs/options/tooltip/)

 

> **enabledOnSeries: Array**
Show tooltip only on certain series in a multi-series chart. _Provide indices of those series which you would like to be shown._

**Comment by junedchhipa** [comment]
Thanks for the catch!
Fixed it.
