### ISSUE TITLE
Angular not supporting realtime chart

### ISSUE THREAD

**Issue by richardmtp** [apexcharts/ng-apexcharts#46]
Could you please consider realtime chart for angular framework

**Comment by chaitanyasairam-d** [comment]
I am getting 562X562 matrix. It is not loding

**Comment by HannesJo0139** [comment]
Works the same way as for apexcharts js

**Comment by shreyasssk** [comment]
@HannesJo0139 could you please guide me on how to display realtime data, I'm stuck

**Comment by HannesJo0139** [comment]
@shreyasssk Well I'm not really having the time to setup a minimum example for you. But you basically just setup the chart and then use the method updateSeries() in an interval to apply new data. Where are you stuck exactly?

**Comment by shreyasssk** [comment]
@HannesJo0139 Hi thanks for reaching back, unfortunately, apexcharts does not work for Angular real-time. So I built the app using React. And it's working just fine. Cheers!

**Comment by HannesJo0139** [comment]
Fine if you found another solution. Just for your info and for any readers: It is not true. I am using real-time plots in angular the same way it is told in the apexcharts docs. It is definitely working.

**Comment by mohit-sojitra** [comment]
Could you please upload any snap shot of the solution so we can understand?

**Comment by HannesJo0139** [comment]
Unfortunately I cannot provide the whole project since I am not the only contributor. Best I can do is give you the component as it is completely written by me. The method `updateChart()` is propably where you want to start.

[metrics-view.zip](https://github.com/apexcharts/ng-apexcharts/files/8316074/metrics-view.zip)

**Comment by marcioggs** [comment]
Possibly related to:
https://github.com/apexcharts/ng-apexcharts/issues/274

Check the first comment there for a possible solution.
