### ISSUE TITLE
Create/update changelog

### ISSUE THREAD

**Issue by Carniatto** [apexcharts/ng-apexcharts#47]
For people wondering if the latest release would introduce any breaking change that might break their code would be very useful to have a changelog

**Comment by junedchhipa** [comment]
Hey @Carniatto 
Most of the major release notes are written in the core apexcharts library release page - https://github.com/apexcharts/apexcharts.js/releases

The wrapper libraries seldom have any breaking change until now. But, those changes will also be written in the core release (if any)

Thanks for the suggestion.

**Comment by sandrooco** [comment]
@junedchhipa where do we find changelogs for the more current releases? Thanks in advance.
