### ISSUE TITLE
Resize

### ISSUE THREAD

**Issue by antoniorib91** [apexcharts/ng-apexcharts#51]
Hello, check this issue on apexchartsjs: https://github.com/apexcharts/apexcharts.js/issues/330, I facing the same throuble with ng-apexcharts.
For some reason, my chart doesn't resize when my div resize. If I use devtools and resize reduce the screen size, the chart update size.

**Comment by junedchhipa** [comment]
Can you please create a reproducible example on codesandbox?
There are a lot of samples for [angular apexcharts on codesandbox](https://codesandbox.io/s/apx-line-basic-o2mwb), so you might start from there.

**Comment by antoniorib91** [comment]
@junedchhipa , I created a sandbox here https://codesandbox.io/s/blissful-thunder-31vdh with the sample. If you click menu button, to reduce menu size, the cart doesn't resize, but if you resize the window pulling a little of the code area to the left for example, I the chart resize.

**Comment by junedchhipa** [comment]
It's because, when you hide/show the menu, only the width of the menu is affected.
The parent of the chart doesn't get affected by your menu interaction.

The chart will only resize if its parent size gets changed. Try to come up with a solution where your menu actually changes the content container and you'll see it automatically re-renders on parent size change.

I hope this clears things up.

**Comment by antoniorib91** [comment]
Please, checke again the sample, I uptated changing the menu and content width. When I put new class in content with new witdh the chart not resize.

**Comment by Nishanth15** [comment]
@antoniorib91, Could you solve the above scenario?

**Comment by antoniorib91** [comment]
Hello, I solved reloading all the chart

**Comment by EmmaProject** [comment]
> It's because, when you hide/show the menu, only the width of the menu is affected.
> The parent of the chart doesn't get affected by your menu interaction.
> 
> The chart will only resize if its parent size gets changed. Try to come up with a solution where your menu actually changes the content container and you'll see it automatically re-renders on parent size change.
> 
> I hope this clears things up.

In fact, when i open my drawer, it resizes all the content but teh chart dont,  when i resize the window it resizes correctly...
do you know how can i solve this?, it think its a listener problem

**Comment by junedchhipa** [comment]
Please see if the solution in https://github.com/apexcharts/apexcharts.js/issues/1584 can solve your issues.

> One workaround is to add overflow: hidden to the parent flex container.

> ```
> .v-card {
>    overflow: hidden;
> }
> ```

**Comment by Nishanth15** [comment]
> In fact, when i open my drawer, it resizes all the content but teh chart dont, when i resize the window it resizes correctly...
> do you know how can i solve this?, it think its a listener problem

@EmmaProject , If you are using bootstrap. You can add `mx-auto` for the container of `apx-chart`. It solved the issue in my case

**Comment by parthdevloper** [comment]
> > It's because, when you hide/show the menu, only the width of the menu is affected.
> > The parent of the chart doesn't get affected by your menu interaction.
> > The chart will only resize if its parent size gets changed. Try to come up with a solution where your menu actually changes the content container and you'll see it automatically re-renders on parent size change.
> > I hope this clears things up.
> 
> In fact, when i open my drawer, it resizes all the content but teh chart dont, when i resize the window it resizes correctly...
> do you know how can i solve this?, it think its a listener problem

There are two solutions for this
1. with `updateOptions`
2. update `charts prop` dynamically

> 1.

```
  <apx-chart
          #referenceRef
          [series]="data.subscribers_gained.series"
          [chart]="gainedChartoptions.chart"
          [stroke]="gainedChartoptions.stroke"
          [fill]="gainedChartoptions.fill"
          [tooltip]="gainedChartoptions.tooltip"
          [colors]="gainedChartoptions.colors"
          [dataLabels]="gainedChartoptions.dataLabels"
        ></apx-chart>
```

```
@ViewChild('referenceRef') referenceRef: any;

  ngAfterViewInit() {
  
  // change setTimeout with the subscription  or the method or the event where you want to reRender the chart
    setTimeout(() => {
      this.refe.updateOptions({});
    }, 15000);
  }
```

> 2. This will rerender the chart when the parent container size changes

```
      <div id="gainedChartoptions" #containerRef >
        <apx-chart
          [series]="data.subscribers_gained.series"
          [chart]="{
            width: containerRef.offsetWidth
            height: 100,
            type: 'area',
            toolbar: {
              show: false
            },
            sparkline: {
              enabled: true
            }
          }"
          [stroke]="gainedChartoptions.stroke"
          [fill]="gainedChartoptions.fill"
          [tooltip]="gainedChartoptions.tooltip"
          [colors]="gainedChartoptions.colors"
          [dataLabels]="gainedChartoptions.dataLabels"
        ></apx-chart>
      </div>
```
Any doubts? connect here: https://stackoverflow.com/users/12466554/parth-devloper

**Comment by ajaypatelaj** [comment]
> Please see if the solution in [apexcharts/apexcharts.js#1584](https://github.com/apexcharts/apexcharts.js/issues/1584) can solve your issues.
> 
> > One workaround is to add overflow: hidden to the parent flex container.
> 
> > ```
> > .v-card {
> >    overflow: hidden;
> > }
> > ```

This solution won't work for me.
