### ISSUE TITLE
Angular 9 compatibility

### ISSUE THREAD

**Issue by mits87** [apexcharts/ng-apexcharts#53]
Hi, 

can you add compatibility with Angular 9?
Currently when I'm doing npm install I'm getting those warnings:

> npm WARN ng-apexcharts@1.2.1 requires a peer of @angular/common@^8.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN ng-apexcharts@1.2.1 requires a peer of @angular/core@^8.0.0 but none is installed. You must install peer dependencies yourself.
> 

Thank you in advance.

**Comment by rokerkony** [comment]
the same applies now for Angular 10

**Comment by junedchhipa** [comment]
The PR #69 by @sp90 fixes this.
Can you please upgrade to the latest version 1.5.0 and check again?

**Comment by rokerkony** [comment]
@junedchhipa not really, there was allowed only ng9. I created a PR: https://github.com/apexcharts/ng-apexcharts/pull/80

You will just need to publish a new version afterwards

**Comment by rokerkony** [comment]
Hey @junedchhipa, thank you for merging my PR. Just a question, when can we expect a new version released?

**Comment by junedchhipa** [comment]
New version `ng-apexcharts@1.5.1` released
