### ISSUE TITLE
Firefox: Chart is not shown in non-visible Angular Material tab

### ISSUE THREAD

**Issue by antonbarada** [apexcharts/ng-apexcharts#61]
Using Angular Material tabs apexchart is not shown in non-visible tab and there is error in console

Error:
![angular-vxb8tb - StackBlitz 2020-04-03 16-20-21](https://user-images.githubusercontent.com/9532838/78365541-e50d0980-75c7-11ea-8272-2073181b305f.png)

Demo: https://stackblitz.com/edit/angular-vxb8tb

**Comment by sp90** [comment]
I think angular material might have fixed it. Because it does work on your stackblitz link.

<img width="1852" alt="Screenshot 2020-05-27 at 11 14 32" src="https://user-images.githubusercontent.com/3041602/83000919-4d49fb80-a00b-11ea-8a68-ed98826676a5.png">

**Comment by sp90** [comment]
@junedchhipa maybe we should close this one

**Comment by lamzarescu** [comment]
Try lazy-loading on each mat-tab. In this way, your charts will wait for each tab to render, avoiding background rendering, which cause the error on Firefox.

```
<mat-tab>
     <ng-template matTabContent>
              ...
     </ng-template>
</mat-tab>
```
