### ISSUE TITLE
Custom Tooltip issue with capturing component variables

### ISSUE THREAD

**Issue by b0** [apexcharts/ng-apexcharts#62]
Hello,

I was trying to make a custom tooltip but the one that can show some variable values from my Angular component - but, it doesn't work.

Since it's pretty hard to explain in writing, I have forked yours [area-basic](https://codesandbox.io/s/apx-area-basic-qyhml) CodeSandbox [here](https://codesandbox.io/s/apx-area-basic-9yybq) and added tooltip config.

You can check _src/App/app.component.ts_ on line 84 that custom tooltip function _getTooltip1_ is set and working, but if you try and change it to _getTooltip2_ it doesn't work because _this.message_ is undefined when called from ApexCharts...

Could you please look at that example and  see if there is a solution to this issue?

Thank you

**Comment by bpenovic** [comment]
Hy,
first of all, you have to fix `message: 'Hi there'` with `message = 'Hi there'`.
The problem why your variable is undefined is because of variable Scope. You are calling method Return from method GetTooltip and trying to get variable from out scope. 

One easy solution is to use JavasScript Closure  

        custom: ({ series, seriesIndex, dataPointIndex, w }) => {  
          let currentMessage = this.message;  
          return (  
            '<div class="arrow_box">' +  
            "<span> " +  
            series[seriesIndex][dataPointIndex] +  
            currentMessage +  
            "</span>" +  
            "</div>"  
          );  
        }

**Comment by b0** [comment]
Thank you @bpenovic . 

@junedchhipa , are there another, recommended way to do this ?

Thank you

**Comment by junedchhipa** [comment]
@b0 What @bpenovic has suggested is one of the recommended ways to preserve the `this` context.
I would go with that.
