### ISSUE TITLE
Chart does not load with height: '100%'

### ISSUE THREAD

**Issue by Carniatto** [apexcharts/ng-apexcharts#65]
# Actual
does not load the chart at all
![image](https://user-images.githubusercontent.com/1366831/80608704-d2a7b380-8a3f-11ea-9d71-ae04719e3017.png)

# Expected
renders taking the whole size of the container if the container has a fixed height

# Reproduction
https://codesandbox.io/s/apx-stepline-yz53v?file=/src/app/app.component.ts

**Comment by Carniatto** [comment]
@junedchhipa I've checked the code on this repo and seems that this could be a problem on the `apexcharts` library indeed

**Comment by pacocom** [comment]
I have the same problem!

**Comment by FuelKubitox** [comment]
Same problem. Cant set height 100%. Any workarounds?

**Comment by Witzler** [comment]
Also experienced this problem, couldn't figure out a workaround. Would enjoy a fix for that!
