### ISSUE TITLE
unable to change colors for Range Bar 

### ISSUE THREAD

**Issue by chaitanyasairam-d** [apexcharts/ng-apexcharts#75]
for rangeBar there is no possibility to change colors

**Comment by junedchhipa** [comment]
What have you tried?
The examples on the [website](https://apexcharts.com/javascript-chart-demos/timeline-charts/) illustrate different ways to change colors.

**Comment by chaitanyasairam-d** [comment]
https://apexcharts.com/angular-chart-demos/column-charts/range-column-chart/


This is the chart i am using

**Comment by junedchhipa** [comment]
You can use the colors property to change the colors

```javascript
this.chartOptions = {
  colors: ['#eee', '#888']
};
```

**Comment by chaitanyasairam-d** [comment]
I tried that but it didnt worked so i changed the graph. Now there is no issue. Thank you for your quick response
