### ISSUE TITLE
SVG is not defined

### ISSUE THREAD

**Issue by juniorschen** [apexcharts/ng-apexcharts#78]
Hello I'm trying to use your lib, but in prod env it always happens:
![image](https://user-images.githubusercontent.com/46031261/87318956-6812f980-c4ff-11ea-928a-d15d5dc45632.png)
This is my versions (in node_modules):
![image](https://user-images.githubusercontent.com/46031261/87319135-9d1f4c00-c4ff-11ea-95e9-cda217a42770.png)
![image](https://user-images.githubusercontent.com/46031261/87319194-af998580-c4ff-11ea-84c9-8a4062571133.png)
And configuration of angular json:
![image](https://user-images.githubusercontent.com/46031261/87319672-4fefaa00-c500-11ea-8a3f-16d244c2bc1c.png)

My angular version is 8.

It seems that there is an error or problem with the use of SVGJS, but I would like to know how to solve this in order to use your graphics in productions

**Comment by junedchhipa** [comment]
Can you please upgrade ng-apexcharts to 1.5.0 and check again?

**Comment by juniorschen** [comment]
Yes everything is working fine now, thanks for the correction and the work

**Comment by shadowintel** [comment]
it is same ssr
