### ISSUE TITLE
toggleSeries(), hideSeries() and other ChartComponent methods not working properly programmatically

### ISSUE THREAD

**Issue by dmitrye** [apexcharts/ng-apexcharts#83]
When trying to access these via the .ts component file during AfterViewInit or OnChanges these methods return undefined. Accessing the same methods via a template/html button click events succeeds. There seems to be a race condition in creating the chartObj inside the component whereby the methods are undefined until after everything has loaded. 

https://codesandbox.io/s/apx-area-spline-toggleseries-xdznq

Discovered while trying to achieve:
I'm trying to have a Spline chart with 7 series and default the initial state to only show 1 series out of the 7 when it first loads. I am also trying to change the legend behavior so that clicking on Series 1 will disable Series 2 (and remaining series).

**Comment by msbatarce** [comment]
I think ive read in another place that the creation of the chartObject is run as a micro-task, so it will only take place at the end of the event loop. If that the case it should work with a setTimout(chartObj.hideSeries(), 0) or with a Promise.resolve() to push the execution to the start of the next loop or the end of the current
