### ISSUE TITLE
angular 10 chart render and destroy errors

### ISSUE THREAD

**Issue by MatejBivr** [apexcharts/ng-apexcharts#84]
hi!
I got a few issues not sure they are related.
when the component with the apex pie chart mounts, the chart renders but i get this error in the console: `ERROR Error: Uncaught (in promise): TypeError: can't access property "f", e is null create@...`
when i unmount the component i get the error: `ERROR Error: Uncaught (in promise): TypeError: can't access property "style", this.w.globals.dom.Paper.node.parentNode.parentNode is null value@...`
on both ng serve and ng build i get no errors in the terminal just a warning:
`WARNING in /home/matej/Projects/dropless/dashboard/node_modules/ng-apexcharts/__ivy_ngcc__/fesm2015/ng-apexcharts.js depends on 'apexcharts/dist/apexcharts.min.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies`
I'm currently using angular 10, but i had the same issue when i bumped the version from 9. any help would be greatly appreciated

package.json: 
`  "@angular/animations": "^10.0.5",
    "@angular/cdk": "^10.1.0",
    "@angular/common": "^10.0.5",
    "@angular/compiler": "^10.0.5",
    "@angular/core": "^10.0.5",
    "@angular/forms": "^10.0.5",
    "@angular/localize": "^10.0.5",
    "@angular/platform-browser": "^10.0.5",
    "@angular/platform-browser-dynamic": "^10.0.5",
    "@angular/platform-server": "^10.0.5",
    "@angular/router": "^10.0.5",
   ...
   "ng-apexcharts": "^1.5.0",
   "apexcharts": "^3.19.3",
`

**Comment by mokeev1995** [comment]
FYI: warning was fixed in #79

**Comment by junedchhipa** [comment]
Please upgrade to `apexcharts@3.20.0` and `ng-apexcharts@1.5.1` and report back if it fixes the issue.

**Comment by mokeev1995** [comment]
@junedchhipa did you publish 1.5.1?
NPM doesn't show it if you did and that's a bit strange.

![image](https://user-images.githubusercontent.com/8450876/89031638-8d936600-d33b-11ea-8467-a9c32b1b34ed.png)

**Comment by junedchhipa** [comment]
It shows now.
Maybe it takes some time to reflect.

![Screenshot 2020-07-31 at 5 25 22 PM](https://user-images.githubusercontent.com/17950663/89032674-d276c700-d352-11ea-8e0a-bf964ca8157b.png)

**Comment by mokeev1995** [comment]
oh, yeah, now it's there. thanks.
