### ISSUE TITLE
how to change in css?

### ISSUE THREAD

**Issue by ayaz2929** [apexcharts/ng-apexcharts#85]
i am unable to edit the tooltip css. whats the method to do it in angular?

**Comment by mokeev1995** [comment]
Did you try disable "view encapsulation" for your component where apexcharts is used?

```ts
// ...
@Component({
  // ...
  encapsulation: ViewEncapsulation.None
  // ...
})
class MyComp {
  // ...
}
```

**Comment by ayaz2929** [comment]
thankyou soo much !! its working now

> Did you try disable "view encapsulation" for your component where apexcharts is used?
> 
> ```ts
> // ...
> @Component({
>   // ...
>   encapsulation: ViewEncapsulation.None
>   // ...
> })
> class MyComp {
>   // ...
> }
> ```

thankyou soo much its working now
