### ISSUE TITLE
UPGRADE to ANGULAR 10 : warning : entry point "ng-apexcharts" 

### ISSUE THREAD

**Issue by parthdevloper** [apexcharts/ng-apexcharts#87]
Recently I upgraded my angular 9 to angular 10.

When I compile with ```ng s```, I am getting the following error.

**Warning: Entry point 'ng-apexcharts' contains deep imports into 'my_path/node_modules/apexcharts/dist/apexcharts.min.js'. This is probably not a problem, but may cause the compilation of entry points to be out of order.**

![image](https://user-images.githubusercontent.com/58413215/88937222-79028f80-d2a1-11ea-8d75-71954bbd138d.png)

I already updated ```ng-apexcharts```  & ```apexcharts``` to the latest. Anyone getting the same ?? & solution ??

My stack : 

```
...
"ng-apexcharts": "^1.5.0",
"apexcharts": "^3.19.3"
...
```

**Comment by mokeev1995** [comment]
Duplicate #72 , fix is provided in #79. Waiting for PR merge.

**Comment by junedchhipa** [comment]
Released `apexcharts@3.20.0` and `ng-apexcharts@1.5.1`.
Please upgrade and report back if it fixes the issue
