### ISSUE TITLE
Can we have some configurable throttling for resize event in charts?

### ISSUE THREAD

**Issue by indrajitbnikam** [apexcharts/ng-apexcharts#90]
Hi @junedchhipa ,

I am using ng-apexcharts in my application. It's pretty beautiful.

I have a use case though where the parent containing these charts is resize-able, and Since I am using multiple charts they are getting re-rendered on every such event.

This is causing huge performance toll on the application. Can I somehow throttle this resize event so that there is not such performance issue.

Let me know if and how I can contribute for this problem, I would like to 😊.

**Comment by junedchhipa** [comment]
```javascript
chart: {
  redrawOnParentResize: false
}
```

https://apexcharts.com/docs/options/chart/redrawonparentresize/

**Comment by indrajitbnikam** [comment]
But then how should render the charts on resize?

**Comment by junedchhipa** [comment]
On window resize, the chart will still update. The property prevents the chart from updating if the dimensions of the parent of the chart change.

To forcefully update the chart, you can use the `updateOptions` function

```javascript
   this.chart.updateOptions({})
```

https://github.com/apexcharts/ng-apexcharts#calling-core-apexcharts-methods
