### ISSUE TITLE
"Cannot read property 'removeEventListener' of null"

### ISSUE THREAD

**Issue by MichalNemec** [apexcharts/ng-apexcharts#91]
same as in https://github.com/apexcharts/vue-apexcharts/issues/275

**Comment by IsaacSomething** [comment]
I wonder if it has anything to do with 

```
 public destroy() {
    this.chartObj.destroy();
  }
```
on line 234 in `chart.component.ts`, maybe a check for `this.chartObj` is needed there

**Comment by peteichuk** [comment]
This bug in apexcharts.js. [Issue](https://github.com/apexcharts/apexcharts.js/issues/1891)

**Comment by junedchhipa** [comment]
This has been fixed.
