### ISSUE TITLE
bar charts colors wont change

### ISSUE THREAD

**Issue by dstrohschein** [apexcharts/ng-apexcharts#99]
I am providing a list of different colors to the color property, but it only uses the first one. If i use a function for the colors property, and pass kn the current index, its always 0 despite there being many more elements in the data array. Not sure what the issue is, but this doesn't appear to be right.

**Comment by junedchhipa** [comment]
Can you create a simple Codepen of what you've tried?

If you're using a column chart, you have to set `plotOptions.bar.distributed: true` to get different colors.

**Comment by dstrohschein** [comment]
> Can you create a simple Codepen of what you've tried?
> 
> If you're using a column chart, you have to set `plotOptions.bar.distributed: true` to get different colors.

That could be the problem - as I am not setting that. But that is not in the documentation for colors, or for the bar chart. I would suggest to add that to the documentation so others do not fall in to the same problem.
